FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["TaskManager.csproj", "./"]
RUN dotnet restore "./TaskManager.csproj"
COPY . .
RUN dotnet tool install --global dotnet-ef --version 8.0.7
RUN /root/.dotnet/tools/dotnet-ef migrations add InitialCreate --project TaskManager.csproj -v

WORKDIR "/src/."
RUN dotnet build "TaskManager.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "TaskManager.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaskManager.dll"]