version: "3.4"

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      DATABASE: "TaskManagerDB"
    ports:
      - "1433:1433"

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8000:8080"

volumes:
  mssql_data:
